## Deliverable 2. Create a Customer Travel Destinations Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps
import numpy as np

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

In [2]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv("../Weather_Database/WeatherPy_database.csv")
city_data_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Meulaboh,ID,4.1363,96.1285,84.06,64,27,3.13,scattered clouds
1,1,Trairi,BR,-3.2778,-39.2689,76.66,90,100,4.52,overcast clouds
2,2,Olafsvik,IS,64.8945,-23.7142,28.94,74,100,13.87,overcast clouds
3,3,Punta Arenas,CL,-53.1500,-70.9167,44.60,61,0,4.61,clear sky
4,4,Cape Town,ZA,-33.9258,18.4232,66.20,77,75,9.22,broken clouds

In [3]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
mintemp=float(input("What is the minimum temperature you would like for your trip? "))
maxtemp=float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 60
What is the maximum temperature you would like for your trip? 90

In [4]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
prefertemp_city_df=city_data_df.loc[(city_data_df["Max Temp"] <=maxtemp) & (city_data_df["Max Temp"] >= mintemp)]
prefertemp_city_df.head()

,City_ID,City,Country,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Current Description
0,0,Meulaboh,ID,4.1363,96.1285,84.06,64,27,3.13,scattered clouds
1,1,Trairi,BR,-3.2778,-39.2689,76.66,90,100,4.52,overcast clouds
4,4,Cape Town,ZA,-33.9258,18.4232,66.20,77,75,9.22,broken clouds
5,5,Hermanus,ZA,-34.4187,19.2345,63.00,94,99,5.19,overcast clouds
6,6,Butaritari,KI,3.0707,172.7902,80.91,80,85,11.83,overcast clouds

In [5]:
# 4a. Determine if there are any empty rows.
prefertemp_city_df.isnull().sum()

City_ID                0
City                   0
Country                5
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Current Description    0
dtype: int64

In [6]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df=prefertemp_city_df.dropna()

In [7]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Current Description", "Lat", "Lng"]].copy()

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = np.nan
hotel_df.head(10)

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
0,Meulaboh,ID,84.06,scattered clouds,4.1363,96.1285,NaN
1,Trairi,BR,76.66,overcast clouds,-3.2778,-39.2689,NaN
4,Cape Town,ZA,66.20,broken clouds,-33.9258,18.4232,NaN
5,Hermanus,ZA,63.00,overcast clouds,-34.4187,19.2345,NaN
6,Butaritari,KI,80.91,overcast clouds,3.0707,172.7902,NaN
7,Hobart,AU,64.00,clear sky,-42.8794,147.3294,NaN
8,Busselton,AU,71.01,clear sky,-33.6500,115.3333,NaN
9,Mahebourg,MU,80.60,light rain,-20.4081,57.7000,NaN
11,Bengkulu,ID,84.47,broken clouds,-3.8004,102.2655,NaN
12,Puerto Ayora,EC,75.99,overcast clouds,-0.7393,-90.3518,NaN

In [8]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

print("Beginning Data Retrieval     ")
print("-----------------------------")

# 6b. Iterate through the hotel DataFrame.
for index, row in hotel_df.iterrows():
    # 6c. Get latitude and longitude from DataFrame
    lat = row["Lat"]
    lng = row["Lng"]
    params["location"] = f"{lat},{lng}"
    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    base_url="https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    # 6e. Make request and retrieve the JSON data from the search. 
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        print(f"Hotel found.")
    except (IndexError):
        print("Hotel is not found... skipping.")
print("-----------------------------")
print("Data Retrieval Complete      ")
print("-----------------------------")

Beginning Data Retrieval
-----------------------------
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel is not found... skipping.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel is not found... skipping.
Hotel is not found... skipping.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel is not found... skipping.
Hotel found.
Hotel found.
Hotel found.
Hotel is not found... skipping.
Hotel is not found... skipping.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel is not found... skipping.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel is not found... skipping.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel is not found... skipping.
Hotel found.
Hotel is not found... skipping.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel is not found... skipping.
Hotel found.
Hotel found.
Hotel found.
Hotel is not found... skipping.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel is not found... skipping.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel is not found... skipping.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel is not found... skipping.
Hotel is not found... skipping.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
Hotel found.
-----------------------------
Data Retrieval Complete
-----------------------------

In [9]:
# 7. Drop the rows where there is no Hotel Name.
#hotel_list_df=hotel_df.dropna()

hotel_list_df=hotel_df.dropna()

In [10]:
# 8a. Create the output File (CSV)
output_data_file = "../Vacation_Search/WeatherPy_vacation.csv"
# 8b. Export the City_Data into a csv
hotel_list_df.to_csv(output_data_file, index_label="City_ID")

In [11]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Weather</dt><dd>{Current Description} and {Max Temp}°F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in hotel_list_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = hotel_list_df[["Lat", "Lng"]]

In [12]:
# 11a. Add a marker layer for each city to the map. 

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1)
heat_layer = gmaps.heatmap_layer(locations,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))